import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ReactNode } from 'react';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex max-w-[1280px] mx-auto m flex-col min-h-screen p-4 pb-20 sm:p-20 font-[family-name:var(--font-geist-sans)]  ">
          <header className="border-b-2 border-gray-500 mb-5 bor ">
            <h1 className=" w-full text-5xl  font-bold uppercase p-2">
              the Car Dealer App
            </h1>
          </header>

          <main className="  flex flex-col gap-8 row-start-2 items-center   sm:items-start ">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
